const tableData = [
    { type: 'start', id: 0, name: 'GO', buyable: false },
    { type: 'property', id: 1, name: 'Mediterranean Avenue', cost: 60, rent: 2, owner: null, buyable: true },
    { type: 'communityChest', id: 2, name: 'Community Chest', buyable: false },
    { type: 'property', id: 3, name: 'Baltic Avenue', cost: 60, rent: 4, owner: null, buyable: true },
    { type: 'tax', id: 4, name: 'Income Tax', buyable: false },
    { type: 'railroad', id: 5, name: 'Reading Railroad', cost: 200, owner: null, buyable: true },
    { type: 'property', id: 6, name: 'Oriental Avenue', cost: 100, rent: 6, owner: null, buyable: true },
    { type: 'chance', id: 7, name: 'Chance', buyable: false },
    { type: 'property', id: 8, name: 'Vermont Avenue', cost: 100, rent: 6, owner: null, buyable: true },
    { type: 'property', id: 9, name: 'Connecticut Avenue', cost: 120, rent: 8, owner: null, buyable: true },
    { type: 'jail', id: 10, name: 'Jail', buyable: false },
    { type: 'property', id: 11, name: 'St. Charles Place', cost: 140, rent: 10, owner: null, buyable: true },
    { type: 'utility', id: 12, name: 'Electric Company', cost: 150, owner: null, buyable: true },
    { type: 'property', id: 13, name: 'States Avenue', cost: 140, rent: 10, owner: null, buyable: true },
    { type: 'property', id: 14, name: 'Virginia Avenue', cost: 160, rent: 12, owner: null, buyable: true },
    { type: 'railroad', id: 15, name: 'Pennsylvania Railroad', cost: 200, owner: null, buyable: true },
    { type: 'property', id: 16, name: 'St. James Place', cost: 180, rent: 14, owner: null, buyable: true },
    { type: 'communityChest', id: 17, name: 'Community Chest', buyable: false },
    { type: 'property', id: 18, name: 'Tennessee Avenue', cost: 180, rent: 14, owner: null, buyable: true },
    { type: 'property', id: 19, name: 'New York Avenue', cost: 200, rent: 16, owner: null, buyable: true },
    { type: 'freeParking', id: 20, name: 'Free Parking', buyable: false },
    { type: 'property', id: 21, name: 'Kentucky Avenue', cost: 220, rent: 18, owner: null, buyable: true },
    { type: 'chance', id: 22, name: 'Chance', buyable: false },
    { type: 'property', id: 23, name: 'Indiana Avenue', cost: 220, rent: 18, owner: null, buyable: true },
    { type: 'property', id: 24, name: 'Illinois Avenue', cost: 240, rent: 20, owner: null, buyable: true },
    { type: 'railroad', id: 25, name: 'B. & O. Railroad', cost: 200, owner: null, buyable: true },
    { type: 'property', id: 26, name: 'Atlantic Avenue', cost: 260, rent: 22, owner: null, buyable: true },
    { type: 'property', id: 27, name: 'Ventnor Avenue', cost: 260, rent: 22, owner: null, buyable: true },
    { type: 'utility', id: 28, name: 'Water Works', cost: 150, owner: null, buyable: true },
    { type: 'property', id: 29, name: 'Marvin Gardens', cost: 280, rent: 24, owner: null, buyable: true },
    { type: 'goToJail', id: 30, name: 'Go To Jail', buyable: false },
    { type: 'property', id: 31, name: 'Pacific Avenue', cost: 300, rent: 26, owner: null, buyable: true },
    { type: 'property', id: 32, name: 'North Carolina Avenue', cost: 300, rent: 26, owner: null, buyable: true },
    { type: 'communityChest', id: 33, name: 'Community Chest', buyable: false },
    { type: 'property', id: 34, name: 'Pennsylvania Avenue', cost: 320, rent: 28, owner: null, buyable: true },
    { type: 'railroad', id: 35, name: 'Short Line', cost: 200, owner: null, buyable: true },
    { type: 'chance', id: 36, name: 'Chance', buyable: false },
    { type: 'property', id: 37, name: 'Park Place', cost: 350, rent: 35, owner: null, buyable: true },
    { type: 'luxuryTax', id: 38, name: 'Luxury Tax', buyable: false },
    { type: 'property', id: 39, name: 'Boardwalk', cost: 400, rent: 50, owner: null, buyable: true }
  ];

export default tableData;