export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
      <div className="p-2 w-screen h-screen bg-transparent">{children}</div>
  )
}
