export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="p-2 w-screen h-screen bg-transparent">{children}</body>
    </html>
  )
}
