import { Inter } from 'next/font/google'
import './globals.css'
import RealtimeProvider from '@/components/RealtimeProvider'
import QueryProvider from '@/components/query-provider'
const inter = Inter({ subsets: ['latin'] })
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <RealtimeProvider>
            {children}
          </RealtimeProvider>
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
