import { Inter } from 'next/font/google'
import './globals.css'
import RealtimeProvider from '@/components/RealtimeProvider'

const inter = Inter({ subsets: ['latin'] })
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RealtimeProvider>
          {children}
        </RealtimeProvider>
        <ToastContainer/>
      </body>
    </html>
  )
}
