import RealtimeProvider from "@/components/context/realtime-provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <RealtimeProvider>
      {children}
  </RealtimeProvider>
  )
}
